# Generated by Django 4.2.6 on 2023-11-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cardplan_workouts_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='DueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cardplan'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_payed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='cardplan',
            name='duration',
            field=models.IntegerField(verbose_name='Длительность'),
        ),
    ]
