# Generated by Django 4.2.6 on 2023-11-23 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_card_duedate_card_duration_card_is_payed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardplan',
            options={'verbose_name': 'План абонемента', 'verbose_name_plural': 'Планы абонементов'},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AlterModelOptions(
            name='workouts',
            options={'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='DueDate',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.AddField(
            model_name='card',
            name='IssueDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='is_payed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус оплаты'),
        ),
    ]
