# Generated by Django 4.2.6 on 2023-11-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cardplan_options_alter_coach_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardplan',
            name='duration',
            field=models.CharField(max_length=30, verbose_name='Длительность'),
        ),
    ]
