# Generated by Django 4.2.6 on 2023-11-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_diagram_remove_gym_coahes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coachs/'),
        ),
    ]
