# Generated by Django 4.2.6 on 2023-11-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_gym_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouts',
            name='price',
        ),
        migrations.AddField(
            model_name='gym',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
