# Generated by Django 4.2.6 on 2023-12-01 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_workouts_price_gym_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='gym',
            field=models.ManyToManyField(to='main.gym'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Дата и время тренировки')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coach')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gym')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
