# Generated by Django 4.2.6 on 2023-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_coach_gym_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='schedule',
            field=models.ManyToManyField(related_name='Расписание', to='main.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_busy',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cтатус расписания'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='gym',
            field=models.ManyToManyField(related_name='Залы', to='main.gym'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='workouts',
            field=models.ManyToManyField(related_name='Тренировки', to='main.workouts'),
        ),
    ]
