# Generated by Django 4.2.6 on 2023-12-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_card_schedule_schedule_is_busy_alter_coach_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='is_busy',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.CharField(max_length=30, verbose_name='Время тренировки'),
        ),
    ]
