# Generated by Django 4.2.6 on 2023-12-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_schedule_is_busy_alter_schedule_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='schedule',
        ),
        migrations.AddField(
            model_name='card',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.schedule'),
        ),
    ]
