# Generated by Django 4.2.6 on 2023-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_card_schedule_card_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_busy',
            field=models.BooleanField(blank=True, default=False, verbose_name='Время переполнено'),
        ),
    ]
