# Generated by Django 4.2.6 on 2023-12-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_schedule_number_alter_schedule_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_coach',
            field=models.BooleanField(blank=True, default=False, verbose_name='без тренера'),
        ),
    ]
