# Generated by Django 4.2.6 on 2023-12-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_coach_is_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='experience',
            field=models.CharField(max_length=30, null=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='qualification',
            field=models.CharField(max_length=30, null=True, verbose_name='Специализация'),
        ),
    ]
